# Setup
title:        The Infinite Sadness
tagline:      I'll see you again when the stars fall from the sky
baseurl:      ""
locale:       "en"

paginate:     5

# About/contact
author:
  name:       zc
  url:        https://jschwinger23.github.io/

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
